# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'capture_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(429, 269)
        Form.setStyleSheet("#main_widget{background-color: #1b1b27;}\n"
"#top_widget{background-color: #27263c;}")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.main_widget = QtWidgets.QWidget(Form)
        self.main_widget.setStyleSheet("")
        self.main_widget.setObjectName("main_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.top_widget = QtWidgets.QWidget(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_widget.sizePolicy().hasHeightForWidth())
        self.top_widget.setSizePolicy(sizePolicy)
        self.top_widget.setObjectName("top_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.top_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        self.picamera_frame = QtWidgets.QFrame(self.top_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picamera_frame.sizePolicy().hasHeightForWidth())
        self.picamera_frame.setSizePolicy(sizePolicy)
        self.picamera_frame.setMinimumSize(QtCore.QSize(411, 221))
        self.picamera_frame.setMaximumSize(QtCore.QSize(221, 411))
        self.picamera_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.picamera_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.picamera_frame.setObjectName("picamera_frame")
        
        self.verticalLayout = QtWidgets.QVBoxLayout(self.picamera_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        
        # self.picamera_label = QtWidgets.QLabel(self.picamera_frame)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.picamera_label.sizePolicy().hasHeightForWidth())
        # self.picamera_label.setSizePolicy(sizePolicy)
        # self.picamera_label.setText("")
        # self.picamera_label.setObjectName("picamera_label")
        # self.verticalLayout.addWidget(self.picamera_label)
        
        self.verticalLayout_2.addWidget(self.picamera_frame)
        self.verticalLayout_3.addWidget(self.top_widget)
        self.bottom_widget = QtWidgets.QWidget(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottom_widget.sizePolicy().hasHeightForWidth())
        self.bottom_widget.setSizePolicy(sizePolicy)
        self.bottom_widget.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bottom_widget.setObjectName("bottom_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.bottom_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.closeBtn = QtWidgets.QPushButton(self.bottom_widget)
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout.addWidget(self.closeBtn)
        self.photocapBtn = QtWidgets.QPushButton(self.bottom_widget)
        self.photocapBtn.setObjectName("photocapBtn")
        self.horizontalLayout.addWidget(self.photocapBtn)
        self.verticalLayout_3.addWidget(self.bottom_widget)
        self.verticalLayout_4.addWidget(self.main_widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.closeBtn.setText(_translate("Form", "Close"))
        self.photocapBtn.setText(_translate("Form", "Take a Photo"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())
